// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhNfAnIV8WJErwJNiapSNAapz5SAGiAw',
    appId: '1:275911102106:web:919c5e6364fd4ca2811923',
    messagingSenderId: '275911102106',
    projectId: 'muuwallet-app-project',
    authDomain: 'muuwallet-app-project.firebaseapp.com',
    storageBucket: 'muuwallet-app-project.appspot.com',
    measurementId: 'G-SCQM6R1LFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYBlm-NmJaIxSw9LZrxPT7S-Ron8ftZk',
    appId: '1:275911102106:android:b2e8b50616407b43811923',
    messagingSenderId: '275911102106',
    projectId: 'muuwallet-app-project',
    storageBucket: 'muuwallet-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wUHuorPR501ouq6aKCZAdZwR6fGozno',
    appId: '1:275911102106:ios:87776eee42efc0e3811923',
    messagingSenderId: '275911102106',
    projectId: 'muuwallet-app-project',
    storageBucket: 'muuwallet-app-project.appspot.com',
    iosClientId: '275911102106-rvtf1rfv8o378oo477pmv1lnbs0ig9f4.apps.googleusercontent.com',
    iosBundleId: 'com.devmarkaz.muuwallet',
  );
}
